# Generated by Django 5.0.3 on 2024-03-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_answer_description_alter_exam_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
