# Generated by Django 5.0.3 on 2024-03-19 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_alter_exam_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx", "xls"]
                    )
                ],
            ),
        ),
    ]
