# Generated by Django 5.0.3 on 2024-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_exam_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
