# Generated by Django 5.0.3 on 2024-03-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_examattempts"),
        ("users", "0007_rename_faculty_student_stream"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExamAttempts",
            new_name="ExamAttempt",
        ),
    ]
