# Generated by Django 5.0.3 on 2024-03-27 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_rename_examattempts_examattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
