# Generated by Django 5.0.3 on 2024-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0011_examattempt_result_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="full_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
