# Generated by Django 5.0.3 on 2024-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_examattempt_full_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_practice_test",
            field=models.BooleanField(default=False),
        ),
    ]
