# Generated by Django 5.0.3 on 2024-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0013_exam_is_practice_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="time_taken",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
