# Generated by Django 5.0.3 on 2024-03-28 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0015_exam_is_free"),
        ("users", "0008_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a file in .xls or .xlsx format. Other formats are not supported.",
                        null=True,
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xlsx", "xls"]
                            )
                        ],
                    ),
                ),
                ("schedule_date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "exam_duration",
                    models.IntegerField(
                        help_text="Enter the exam duration in minutes."
                    ),
                ),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="live_exams",
                        to="users.stream",
                    ),
                ),
            ],
        ),
    ]
