# Generated by Django 5.0.3 on 2024-03-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0016_liveexam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liveexam",
            old_name="exam_duration",
            new_name="duration",
        ),
        migrations.RemoveField(
            model_name="liveexam",
            name="description",
        ),
        migrations.RemoveField(
            model_name="liveexam",
            name="file",
        ),
        migrations.RemoveField(
            model_name="liveexam",
            name="stream",
        ),
        migrations.RemoveField(
            model_name="liveexam",
            name="title",
        ),
        migrations.AddField(
            model_name="liveexam",
            name="exam",
            field=models.ForeignKey(
                default=1,
                help_text="Choose an existing exam or create a new one.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_exams",
                to="exam.exam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="liveexam",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Leave it blank to let system determine automatically.",
                null=True,
            ),
        ),
    ]
