# Generated by Django 5.0.3 on 2024-03-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0017_rename_exam_duration_liveexam_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveexam",
            name="end_time",
        ),
    ]
