# Generated by Django 5.0.3 on 2024-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0019_remove_liveexam_schedule_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="live_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="liveexam",
            name="duration",
            field=models.IntegerField(
                help_text="Enter the exam duration in minutes.",
                verbose_name="Duration (Minutes)",
            ),
        ),
    ]
