# Generated by Django 5.0.3 on 2024-03-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_student_teacher_remove_user_is_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
    ]
