# Generated by Django 5.0.3 on 2024-03-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_stream_student_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="users.stream",
            ),
        ),
    ]
