# Generated by Django 5.0.3 on 2024-03-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_student_faculty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="faculty",
            new_name="stream",
        ),
    ]
