# Generated by Django 5.0.3 on 2024-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="has_subscription",
            field=models.BooleanField(default=False),
        ),
    ]
